[project]
name = "kmnlp-infrastructure"
authors = []
maintainers = []
description = "Defines the infrastructure for the KM NLP Project"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
dependencies = [
  "cdktf>=0.21.0, <1.0",
  "cdktf-cdktf-provider-aws>=21.6.0",
  "boto3",
  "boto3-stubs[ec2,ssm]",
  "cdktf-cdktf-provider-helm>=12.0.1",
  "cdktf-cdktf-provider-kubernetes>=12.1.0",
  "cdktf-cdktf-provider-null>=11.0.0",
  "cdktf-cdktf-provider-random",
  "yq>=3.4.3",
  "pydantic>=2.12.1",
]
dynamic = ["version"]

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]

[project.urls]
Gitlab = "https://repo.element84.com/noaa_km_nlp/kmnlp-infrastructure"

[project.optional-dependencies]
dev = [
  "pytest>=8.3.3",
  "ruff>=0.6.8",
  "pyright[nodejs]>=1.1.381",
  "build>=1.2.2",
  "pre-commit>=3.8.0",
  "pre-commit-hooks>=4.6.0",
  "ipython>=8.28.0",
  "ipykernel"
]

[tool.setuptools.packages.find]
exclude = ["vendored"]

[tool.pyright]
ignore = ["**/.venv/**"]
exclude = ["**/node_modules", "**/__pycache__", "**/.*", "**/tests/**", "**/.venv/**", "*.pyc", "imports"]
typeCheckingMode = "strict"
reportImplicitStringConcatenation = "none"
reportPropertyTypeMismatch = "error"
reportShadowedImports = "error"
reportTypedDictNotRequiredAccess = "none"
reportUninitializedInstanceVariable = "error"
reportUnknownArgumentType = "error"
reportUnknownMemberType = "error"
reportUnknownVariableType = "error"
reportUnnecessaryComparison = "error"
reportIncompatibleVariableOverride = "none"


[tool.ruff]
line-length = 100

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
# http://docs.astral.sh/ruff/rules/
select = ['ALL']
ignore = [
  # Unnecessary assignment before return statement
  'RET504',
  # Trailing comma missing
  'COM812',
  # Missing docstring for module
  'D100',
  # Missing docstring in magic method
  'D105',
  # 1 blank line required before class docstring
  'D203',
  # Multi-line docstring summary should start at the second line
  'D213',
  # Undocumented public init
  'D107',
  # Function arg shadowing a python built in. Necessary for CDKTF because it uses 'id' args on init
  'A002',
  # allow long exception messages
  'TRY003',
  # Allow string literals in exceptions.
  'EM101',
  # Allow fstrings in exception messages
  'EM102',
  # TO-DO formatting
  'TD002',
  'TD003',
  'TD004',
  # Allow TO-DOs not be to be an error to break build. We should be able to commit them in features branches
  'FIX002',
  # Too many arguments to function, Terraform CDK classes need lots of arguments.
  'PLR0913'
]

[tool.ruff.lint.per-file-ignores]
'__init__.py' = [
  # Module level import not at top of cell
  'E402',
  # Imported but unused
  'F401',
]
'tests/**/*' = [
  # Use of assert detected
  'S101',
  # Missing return type annotation for public function
  'ANN201',
  # Missing docstrings
  'D1',
  # Private member accessed
  'SLF001',
  # magic values
  'PLR2004',
]
