# Generated automatically by the front-end build.
# From commit: 298d15a0928648641aafe75b8e1b8e3a744df26f
artifact_s3_uri: s3://e84-kmnlp-build-artifacts/frontend/frontend-20260130-213900-298d15a0.tar.gz
